repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: no-commit-to-branch
        name: Don't commit to the default branch
        args: [ --branch, main ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  # Run mypy using the local venv
  # so we don't have to duplicate all typed deps here
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        types_or: [ python, pyi ]
        stages: [ commit ]
        language: system
        entry: poetry run mypy
